GET / HTTP/1.1
Host: localhost:8080
###
GET /applications HTTP/1.1
Host: localhost:8080
###
POST /applications/wl HTTP/1.1
Host: localhost:8080
Content-Type: application/json

{
  "name": "eee",
  "date": "01-01-2020",
  "idea": "viverra nibh cras pulvinar mattis nunc sed blandit libero volutpat sed cras ornare arcu dui vivamus arcu felis bibendum ut",
  "story": "viverra nibh cras pulvinar mattis nunc sed blandit libero volutpat sed cras ornare arcu dui vivamus arcu felis bibendum utviverra nibh cras pulvinar mattis nunc sed blandit libero volutpat sed cras ornare arcu dui vivamus arcu felis bibendum ut",
  "action": "viverra nibh cras pulvinar mattis nunc sed blandit libero volutpat sed cras ornare arcu dui vivamus arcu felis bibendum utviverra nibh cras pulvinar mattis nunc sed blandit libero volutpat sed cras ornare arcu dui vivamus arcu felis bibendum ut",
  "old": 1,
  "know": "viverra nibh cras pulvinar mattis nunc sed blandit libero volutpat sed cras ornare arcu dui vivamus arcu felis bibendum ut",
  "experience": "viverra nibh cras pulvinar mattis nunc sed blandit libero volutpat sed cras ornare arcu dui vivamus arcu felis bibendum ut",
  "dc": "MoneyIgos#2000",
  "hex": "110000100000638"
}
