GET / HTTP/1.1
Host: localhost:8080
###
GET /applications HTTP/1.1
Host: localhost:8080
###
POST /applications/wl HTTP/1.1
Host: localhost:8080
Content-Type: application/json

{
  "name": "eee",
  "date": "01-01-2020",
  "idea": "viverra nibh cras pulvinar mattis nunc sed blandit libero volutpat sed cras ornare arcu dui vivamus arcu felis bibendum ut",
  "story": "viverra nibh cras pulvinar mattis nunc sed blandit libero volutpat sed cras ornare arcu dui vivamus arcu felis bibendum utviverra nibh cras pulvinar mattis nunc sed blandit libero volutpat sed cras ornare arcu dui vivamus arcu felis bibendum ut",
  "action": "viverra nibh cras pulvinar mattis nunc sed blandit libero volutpat sed cras ornare arcu dui vivamus arcu felis bibendum utviverra nibh cras pulvinar mattis nunc sed blandit libero volutpat sed cras ornare arcu dui vivamus arcu felis bibendum ut",
  "old": 1,
  "know": "viverra nibh cras pulvinar mattis nunc sed blandit libero volutpat sed cras ornare arcu dui vivamus arcu felis bibendum ut",
  "experience": "viverra nibh cras pulvinar mattis nunc sed blandit libero volutpat sed cras ornare arcu dui vivamus arcu felis bibendum ut",
  "dc": "MoneyIgos#2000",
  "hex": "110000100000638"
}
###
POST /applications/sup HTTP/1.1
Host: localhost:8080
Content-Type: application/json

{
  "name": "ee",
  "about": "viverra nibh cras pulvinar mattis nunc sed blandit libero volutpat sed cras ornare arcu dui vivamus arcu felis bibendum ut",
  "whyU": "viverra nibh cras pulvinar mattis nunc sed blandit libero volutpat sed cras ornare arcu dui vivamus arcu felis bibendum ut",
  "experienceSup": "viverra nibh cras pulvinar mattis nunc sed blandit libero volutpat sed cras ornare arcu dui vivamus arcu felis bibendum ut",
  "hoursPerDay": 4,
  "old": 12,
  "dc": "MoneyIgos#2000",
  "hex": "110000100000638"
}
###
POST /applications/firm HTTP/1.1
Host: localhost:8080
Content-Type: application/json

{
  "name": "ee",
  "idea": "viverra nibh cras pulvinar mattis nunc sed blandit libero volutpat sed cras ornare arcu dui vivamus arcu felis bibendum ut",
  "owner": "awjdiHkjwdijhw",
  "expects": "viverra nibh cras pulvinar mattis nunc sed blandit libero volutpat sed cras ornare arcu dui vivamus arcu felis bibendum ut",
  "old": 12,
  "type": "viverra nibh cras pulvinar mattis nunc viverra nibh cras pulvinar mattis nunc",
  "headquarters": "eeeeeeeeee",
  "members": 1,
  "dc": "MoneyIgos#2000",
  "hex": "110000100000638"
}
###
POST /auth/admin HTTP/1.1
Host: localhost:8080
Content-Type: application/json

{
  "name": "Jack",
  "pass": "zaq1@WSX"
}
### Valid token
POST /admin/ems HTTP/1.1
Host: localhost:8080
Content-Type: application/json

{
  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoiSmFjayIsImlhdCI6MTYwMjg4MjAwOH0.95EFq-wglXsYIbK0dhbqNP6dbS4lR7wjxASd2jLk4Zg"
}
### Invalid token
POST /admin/sup HTTP/1.1
Host: localhost:8080
Content-Type: application/json

{
  "token": "eyeJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoiSmFjayIsImlhdCI6MTYwMjg4MjAwOH0.95EFq-wglXsYIbK0dhbqNP6dbS4lR7wjxASd2jLk4Zg"
}
###
POST /admin/wl/check HTTP/1.1
Host: localhost:8080
Content-Type: application/json

{
  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoiSmFjayIsImlhdCI6MTYwMjg4MjAwOH0.95EFq-wglXsYIbK0dhbqNP6dbS4lR7wjxASd2jLk4Zg",
  "id": "5f886f6391884d1de0f8afe6",
  "status": "accepted"
}
